apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: wordpress
  name: nfs-storageclass # IMPORTANT pvc needs to mention this name
provisioner: wordpress-nfs # name can be anything
parameters:
  archiveOnDelete: "false"
